Request new license file
spdx/license-list-XML pull request #1240
Opened 2021-04-15 18:00 UTC by jlovejoy

moving request new license to its own document as discussed in #1211 

put here in DOCS or at top-level??

2021-04-15 18:46 UTC, alandtse commented
If we're going to use a DOCS directory, then it makes sense to move everything but standard docs such as README/CONTRIBUTORS to DOCS. This should be fine in DOCS.

2021-04-15 19:19 UTC, mkdolan requested changes
Looks good to me. Suggested a few cleanups.

2021-04-15 19:19 UTC, mkdolan commented on DOCS/request-new-license
> +1.  Review the [license inclusion principles](DOCS/license-inclusion-principles.md).
```suggestion
2.  Review the [license inclusion principles](DOCS/license-inclusion-principles.md).
```

2021-04-15 19:19 UTC, mkdolan commented on DOCS/request-new-license
> +2.  Check the [SPDX License List](https://spdx.org/licenses/), keeping in mind the [SPDX License List Matching Guidelines](https://spdx.org/spdx-license-list/matching-guidelines) and issues labeled [
```suggestion
3.  Check the [SPDX License List](https://spdx.org/licenses/), keeping in mind the [SPDX License List Matching Guidelines](https://spdx.org/spdx-license-list/matching-guidelines) and issues labeled [new license/exception request](https://github.com/spdx/license-list-XML/labels/new%20license%2Fexception%20request) to ensure this license or exception has not been previously requested.
```

2021-04-15 19:19 UTC, mkdolan commented on DOCS/request-new-license
> +3. If your license is not already SPDX License List, submit your request via the SPDX Online Tool [Submit New License](https://tools.spdx.org/app/submit_new_license/) using the guidance provided ther
```suggestion
4. If your license is not already SPDX License List, submit your request via the SPDX Online Tool [Submit New License](https://tools.spdx.org/app/submit_new_license/) using the guidance provided there. Also see the [explanation of the fields contained on the list](DOCS/license-fields.md).
```

2021-04-15 19:19 UTC, mkdolan commented on DOCS/request-new-license
> +4. Submitters are expected to follow and participate in the discussion and answer any request for additional information via the issue and comments. Please note, if submitters are unresponsive for se
```suggestion
5. Submitters are expected to follow and participate in the discussion and answer any request for additional information via the issue and comments. Please note, if submitters are unresponsive for several months, the issue will be closed without making a final decision.
```

2021-04-15 19:35 UTC, bsdimp commented
lgtm

2021-04-16 02:47 UTC, jlovejoy commented
@alandtse 
> If we're going to use a DOCS directory, then it makes sense to move everything but standard docs such as README/CONTRIBUTORS to DOCS. This should be fine in DOCS.

the only thin in the top-level are README, CONTRIBUTING, and RELEASE-NOTES - I think that's what you mean?

2021-04-20 20:06 UTC, silverhook commented on DOCS/request-new-license
> +1. Join the legal team mailing list at lists.spdx.org.
```suggestion
1. Join the [legal team mailing list](https://lists.spdx.org/g/spdx-legal).
```

2021-04-20 22:01 UTC, jlovejoy commented
Thanks for all the feedback. I'm going to merge this so then I'll have a link to add for the CONTRIBUTING page. Any further updates can go for a new PR

2021-04-20 22:11 UTC, merged