Add Community-Spec-1.0
spdx/license-list-XML pull request #1351
Opened 2021-11-02 10:38 UTC by zvr

This PR adds Community-Spec-1.0 (and the corresponding test text file).

Things to note:

- I've added an entry in the `notes` section, pointing to the supporting material, since they were mentioned in #1344.
- The licence text refers to different `.md` files (which are in the supporting material above). Most references seem to have no effect to the license itself, like references to `Notices.md` which lists patents.  However, *Scope* in the license is essentially defined as "look at the other file, `Scope.md`" and *Approved Specification* is also defined as "look at `Governance.md`." Maybe we should have a note that this license text cannot be used standalone, as it _requires_ extra files?
- When transcribing the text, I found two syntax errors. I've opened a [PR](https://github.com/CommunitySpecification/1.0/pull/5) towards the upstream repo about them. If it's merged, the text here must also be changed.
- Four-level deep nested lists are not fun... :unamused:

I apologize for misconstructions in this PR; I'm using the `gh` CLI for all the workflow and still learning...

2021-11-04 14:01 UTC, swinslow commented
Thank you @zvr! I still need to take a look at the commits themselves, but just a couple thoughts on your comments here...

> * The licence text refers to different `.md` files (which are in the supporting material above). Most references seem to have no effect to the license itself, like references to `Notices.md` which lists patents.  However, _Scope_ in the license is essentially defined as "look at the other file, `Scope.md`" and _Approved Specification_ is also defined as "look at `Governance.md`." Maybe we should have a note that this license text cannot be used standalone, as it _requires_ extra files?

I tend to lean towards _not_ getting into this in the notes section. I'd say we don't really want the License List itself to get into the business of opining on _how_ licenses ought to be implemented, e.g. which files the license text should be placed in, etc.

For comparison, in [LGPL-3.0](https://spdx.org/licenses/LGPL-3.0-only.html) we don't have a note to say "you ought to include the GPL-3.0 text as well." I'd kind of lump this together in a similar bucket.

> * When transcribing the text, I found two syntax errors. I've opened a [PR](https://github.com/CommunitySpecification/1.0/pull/5) towards the upstream repo about them. If it's merged, the text here must also be changed.

Yup -- I saw there were a couple of typos as well. If they're merged upstream for what the license steward designates as 1.0, then we can update it here (perhaps with `<alt>` matches to catch both versions). To be honest, I kind of hope that if it's merged upstream that they would designate it with a separate version, e.g. 1.0.1 or 1.1 or something...

2021-11-04 14:05 UTC, swinslow requested changes
Just one comment -- in line 3, the `<license ...>` tag should include an attribute `listVersionAdded="3.15"`.

If you want to add an additional commit to this PR to fix that, feel free. Otherwise, I'll plan to add that as a follow-up PR after we merge this one.

Otherwise, looks good to me -- thanks again @zvr! I'll wait a day or so before merging this PR, in case others have any feedback.

2021-11-09 16:55 UTC, jlovejoy commented
+1 to what @swinslow said above.
Do you want to go head an merge this, or @zvr - are you going to make the minor update on the listVersionAdded="3.15" tag first?

2021-11-09 19:57 UTC, swinslow commented
Just merged the new License List Publisher tools in #1353; after those finish running, I'll plan to merge this next and then update the `listVersionAdded` bit.

2021-11-09 21:04 UTC, zvr commented
The `listVersionAdded` is already there, people: check the commit after @swinslow's comment above.
Sorry for not commenting about it.

2021-11-10 02:17 UTC, swinslow commented
Ah, sorry @zvr -- moving too quickly this morning and I didn't read closely enough. My fault.

Thanks for this! Reviewing and will merge momentarily.

2021-11-10 02:17 UTC, swinslow approved these changes

2021-11-10 02:18 UTC, merged