Add SchemeReport
spdx/license-list-XML pull request #1362
Opened 2021-11-16 15:02 UTC by samth

This adds the SchemeReport license, as discussed in https://github.com/spdx/license-list-XML/issues/1340

Closes #1340.

2021-11-16 15:31 UTC, seabass-labrax requested changes

2021-11-16 15:31 UTC, seabass-labrax commented on src/SchemeReport.xml
> +            name="Scheme Language Report License">
```suggestion
            name="Scheme Language Report License" listVersionAdded="3.16">
```

We'll be publishing SchemeReport in the 3.16 release of the SPDX License List

2021-11-16 15:31 UTC, seabass-labrax commented on src/SchemeReport.xml
> +      </p>
I couldn't find this in the example projects listed in #1340; if it's not part of the license text itself, it should probably go in a `<notes>` element before the `<text>` element.

2021-11-16 15:31 UTC, seabass-labrax commented on test/simpleTestForGenerator/SchemeReport.txt
> +Code derived from the document "Revised Report on Scheme" and subsequent revisions, is distributed under the following license:
If my above review applies, then this line would have to be removed.

2021-11-16 16:02 UTC, samth commented
Thanks @seabass-labrax I've made those changes.

2021-11-16 16:18 UTC, seabass-labrax approved these changes
Thank you @samth! Everything looks great :)

2021-11-17 01:06 UTC, swinslow commented
LGTM, thanks @samth! Tests are passing so I'll go ahead and merge, thanks for preparing this.

2021-11-17 01:06 UTC, merged