Update README.md
spdx/license-list-XML pull request #1670
Opened 2022-10-07 02:11 UTC by jlovejoy

re-order some things into difference sections - thanks to @vmbrasseur  for the jumping off point!

Signed-off-by: Jilayne Lovejoy

2022-10-13 14:58 UTC, swinslow requested changes
A few minor typos, otherwise looks good to me once those are fixes!

2022-10-13 15:14 UTC, jlovejoy commented on DOCS/README.md
> +The files in this folder contains documentation important to understanding the SPDX Licesne List, documentation explaining processes related, and templates to help the community collaborate and provi
fixed!

2022-10-13 15:14 UTC, jlovejoy commented on DOCS/README.md
> +## License submission emplates
fixed

2022-10-13 15:15 UTC, jlovejoy commented on DOCS/README.md
> +* [Submission reponse template](template-license-review-checklist.md) - a 'fill-in-the-blanks' template for responding to new license submissions
fixed

2022-10-26 21:59 UTC, swinslow approved these changes

2022-10-26 21:59 UTC, merged