Improve efficiency of test-one-license
spdx/license-list-XML pull request #1761
Opened 2022-12-26 00:31 UTC by swinslow

Fixes #1760

Signed-off-by: Steve Winslow <steve@swinslow.net>

2022-12-26 00:32 UTC, swinslow commented
@goneall Absolutely no urgency on this one  :)  But I'd welcome your thoughts on this one at some point!

2022-12-26 19:01 UTC, goneall requested changes
This should work with the exception noted below on the test directory parameter - the LicenseListPublisher tools has been updated to test a single license.

The one additional suggestion - you may want to validate the download of the license list publisher using the GPG signature - see https://github.com/spdx/license-list-XML/blob/50f2139df761669d6244825699a08446a547d56b/Makefile#L58

2022-12-27 15:51 UTC, swinslow commented on test-one-license
> +java -jar ${PUBLISHER} TestLicenseXML "src/${@}.xml" "test/simpleTestForGenerator/${@}.txt"
Hi @goneall, I tried changing this to remove the filename from the last parameter, and I'm getting an error message:

```
Test file simpleTestForGenerator is not a valid file
Usage:
TestLicenseXML licenseXmlFile textFile
   licenseXmlFile XML - file to test
   textFile - Text file which should match the the license text for the licenseXmlFile
```

Looking at the LicenseListPublisher code, if I'm reading it correctly, I think it checks to confirm that the specified file actually is a file: see https://github.com/spdx/LicenseListPublisher/blob/f2f481776d149c7d610a2777874abfda87d7dae3/src/org/spdx/licenselistpublisher/LicenseXmlTester.java#L78-L82

I might be misunderstanding, but it looks to me like that command at least is expecting the specific test text file to be provided as an argument?

2022-12-27 15:55 UTC, swinslow commented
Thanks @goneall! For the file vs. directory argument, I just replied inline to the comment above.

For validating the publisher GPG signature, the current PR does the following:
* uses `awk` to extract the TOOL_VERSION from the most current Makefile
* calls `make licenseListPublisher-%.jar-valid` for the TOOL_VERSION as part of downloading the publisher, if it is not already present on disk -- see https://github.com/spdx/license-list-XML/blob/05639a5ddc9294d998863945b06d94aec9ca0c81/test-one-license#L7

Is the call to e.g. `make licenseListPublisher-2.2.7.jar-valid` sufficient to do the GPG validation? It looks like it's occurring when I run it locally, but not sure if I'm missing something.

2022-12-27 18:03 UTC, goneall commented on test-one-license
> +java -jar ${PUBLISHER} TestLicenseXML "src/${@}.xml" "test/simpleTestForGenerator/${@}.txt"
> I might be misunderstanding, but it looks to me like that command at least is expecting the specific test text file to be provided as an argument?

Ahh - I was looking at a different utility that will also test a single file.  You are correct, this command expects a single test file.

My bad - I was looking at the `LicenseRDFAGenerator` which can also take a single file as the input XML but takes a directory for the test files.

2022-12-27 18:05 UTC, goneall commented
> Is the call to e.g. `make licenseListPublisher-2.2.7.jar-valid` sufficient to do the GPG validation? It looks like it's occurring when I run it locally, but not sure if I'm missing something.

You're correct on this one as well, the makefile does validate.  Another miss on the review - I guess I reviewed it a bit too quickly :(

2022-12-27 18:06 UTC, goneall approved these changes
LGTM

2022-12-27 18:11 UTC, swinslow commented
No worries at all, thank you @goneall!

2022-12-27 18:12 UTC, merged