New License: Boehm-GC
spdx/license-list-XML pull request #1999
Opened 2023-06-08 17:31 UTC by jlovejoy

Fixes #1989

Signed-off-by: Jilayne Lovejoy

2023-06-11 20:49 UTC, swinslow requested changes

2023-06-11 20:49 UTC, swinslow commented on src/Boehm-GC.xml
> +         </p>
@jlovejoy I would suggest either omitting lines 22-24 or else making them optional. Neither the Fedora wiki nor libatomic_ops have it. If it's here and not optional then it won't be a match...

2023-06-12 16:55 UTC, jlovejoy commented
@swinslow - made last line optional since it does appear in a standalone license file, I figured that would be the better route. Also added copyright notice template

2023-06-18 13:53 UTC, swinslow approved these changes

2023-06-18 14:31 UTC, merged