extend markup of openvpn-openssl-exception to accomodate psycopg2 ope…
spdx/license-list-XML pull request #2108
Opened 2023-09-05 12:38 UTC by xsuchy

…nssl exception

Fixes: #2038

2023-09-06 20:07 UTC, jlovejoy commented
@swinslow - this looks good to me, agree?

2023-09-10 12:00 UTC, swinslow requested changes
One question as I'm not sure whether this picks up the exact match from #2038 -- please see my comment inline.

2023-09-10 20:40 UTC, xsuchy commented on src/exceptions/openvpn-openssl-exception.xml
> +         than OpenSSL. If you modify this <alt name="file" match="file(\(s\))?">file</alt><alt name="this exception" match="()|( with this exception)"></alt>,
Good catch. Updated.

2023-09-13 10:42 UTC, swinslow approved these changes
LGTM, thanks @xsuchy!

2023-09-13 10:42 UTC, merged